<!DOCTYPE html>
<html>
    <head>

    </head>
    
    <body>

        <h1>Quiz Test File</h1>
        <p>JavaScript starts here:</p>

            <script>
                /*
                const inc    = x => x + 1;
                const double = x => x * 2;

                Function.prototype.then =  fun => x => {
                    console.log(this.result);
                    return fun(x);
                }
                
                Function.constructor.result = this(this.x);


                document.writeln(inc.then(double) (5));  

                const add = x => 5 + x;
                const mult = x => 10 * x;
                let add_ = 5;
                let factor_ = 10;


                -------------------------------
                Provide a function 'failSafe' that - in curried style - takes
                - a default value
                - a callback function
                - an argument to the callback function
                that returns whatever the callback function returns given its argument
                or the default value if the callback function throws an Error.

                Note: see how the tests make use of failSafe.



                 Your solution will be tested against:

                const doError    = x => { throw new Error() };
                const errorCount = failSafe (1) (doError);

                                function doError(arg) {
                    throw "Error";
                }
            
                function errorCount(arg) {
                    return 1;
                }
                document.writeln(failSafe (false) (x=>x) (true));
                document.writeln(failSafe (3) (doError) (null));

                failSafe (false) (x=>x) (true) && failSafe (true) (doError) (null) && errorCount(null) === 1;

                */

                // =====================Q18a===========================
                const failSafe = defVal => callback => arg => {
                    try {
                        return callback(arg)
                    } catch (err) {
                        return defVal;
                    }
                }   
                // ================================================

                const doError    = x => { throw new Error() };
                const errorCount = failSafe (1) (doError);
                document.writeln(failSafe (false) (x=>x) (true) && failSafe (true) (doError) (null) && errorCount(null) === 1);


               

            </script>

    </body>
<html>